# Generated by Django 3.0.8 on 2020-07-17 16:23

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_path_handler, verbose_name='Photo'),
        ),
    ]
