# Generated by Django 3.0.8 on 2020-07-19 13:18

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200719_1200'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='worker',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, head=django.db.models.expressions.F('id')), name='worker_head_not_self'),
        ),
    ]
